apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: websecurityprofiles.k8s.tmlake.com
spec:
  group: k8s.tmlake.com
  names:
    kind: WebSecurityProfile
    listKind: WebSecurityProfileList
    plural: websecurityprofiles
    shortNames:
      - wsp
    singular: websecurityprofile
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - name: profileName
          type: string
          description: the name for websecurityprofile. once define, cannot change
          jsonPath: .spec.name
        - name: ipType
          type: string
          description: the type for websecurityprofile
          jsonPath: .spec.ipType
        - name: uuid
          type: string
          description: the uuid for websecurityprofile. return by ADC api
          jsonPath: .status.uuid
        - name: state
          type: string
          description: the state for websecurityprofile. means the resource is valid/invalid in ADC api
          jsonPath: .status.state
      name: v1
      schema:
        openAPIV3Schema:
          description: WebSecurityProfile resource.
          type: object
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: spec of the WebSecurityProfile resource.
              type: object
              required: [ name,ipType,responseCode,responsePage ]
              properties:
                name:
                  description: 名称
                  type: string
                  pattern: ^[\w-]{1,32}$
                ipType:
                  description: IP类型
                  type: string
                  enum: [ ipv4,ipv6 ]
                responseCode:
                  description: 返回码
                  type: integer
                  enum: [ 400,403,405,406 ]
                responsePage:
                  description: 返回告警页面
                  type: string
                waf:
                  description: waf
                  type: object
                  required: [ wafEnable,wafMode ]
                  properties:
                    wafEnable:
                      description: 是否启用waf
                      type: string
                      enum: [ "on","off" ]
                    wafMode:
                      description: 工作模式
                      type: string
                      enum: [ warning,prevention,prevention+warning ]
                    wafSyslog:
                      description: WAF日志导出
                      type: object
                      properties:
                        enable:
                          description: 是否启用WAF日志导出
                          type: string
                          enum: [ "on","off" ]
                        server:
                          description: Syslog服务器
                          type: object
                          properties:
                            ip:
                              description: IP
                              type: string
                              pattern: ^([0-9]|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.([0-9]|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.([0-9]|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.([0-9]|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])$|^([\da-fA-F]{1,4}:){6}((25[0-5]|2[0-4]\d|[01]?\d\d?)\.){3}(25[0-5]|2[0-4]\d|[01]?\d\d?)$|^::([\da-fA-F]{1,4}:){0,4}((25[0-5]|2[0-4]\d|[01]?\d\d?)\.){3}(25[0-5]|2[0-4]\d|[01]?\d\d?)$|^([\da-fA-F]{1,4}:):([\da-fA-F]{1,4}:){0,3}((25[0-5]|2[0-4]\d|[01]?\d\d?)\.){3}(25[0-5]|2[0-4]\d|[01]?\d\d?)$|^([\da-fA-F]{1,4}:){2}:([\da-fA-F]{1,4}:){0,2}((25[0-5]|2[0-4]\d|[01]?\d\d?)\.){3}(25[0-5]|2[0-4]\d|[01]?\d\d?)$|^([\da-fA-F]{1,4}:){3}:([\da-fA-F]{1,4}:){0,1}((25[0-5]|2[0-4]\d|[01]?\d\d?)\.){3}(25[0-5]|2[0-4]\d|[01]?\d\d?)$|^([\da-fA-F]{1,4}:){4}:((25[0-5]|2[0-4]\d|[01]?\d\d?)\.){3}(25[0-5]|2[0-4]\d|[01]?\d\d?)$|^([\da-fA-F]{1,4}:){7}[\da-fA-F]{1,4}$|^:((:[\da-fA-F]{1,4}){1,6}|:)$|^[\da-fA-F]{1,4}:((:[\da-fA-F]{1,4}){1,5}|:)$|^([\da-fA-F]{1,4}:){2}((:[\da-fA-F]{1,4}){1,4}|:)$|^([\da-fA-F]{1,4}:){3}((:[\da-fA-F]{1,4}){1,3}|:)$|^([\da-fA-F]{1,4}:){4}((:[\da-fA-F]{1,4}){1,2}|:)$|^([\da-fA-F]{1,4}:){5}:([\da-fA-F]{1,4})?$|^([\da-fA-F]{1,4}:){6}:$
                            port:
                              description: 端口
                              type: integer
                              minimum: 1
                              maximum: 65535
                        format:
                          description: 日志格式
                          type: string
                          enum: [ json,text ]
                        template:
                          description: 日志内容
                          type: string
                    wafWhite:
                      description: waf规则
                      type: object
                      properties:
                        invalidList:
                          description: 不生效规则列表
                          type: array
                          items:
                            description: 不生效规则id
                            type: integer
                        wafList:
                          description: 规则列表
                          type: array
                          items:
                            description: 规则详情
                            type: object
                            properties:
                              ruleId:
                                description: 规则id
                                type: integer
                              address:
                                description: 源IP地址
                                type: string
                                pattern: ^([0-9]|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.([0-9]|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.([0-9]|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.([0-9]|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])$|^([\da-fA-F]{1,4}:){6}((25[0-5]|2[0-4]\d|[01]?\d\d?)\.){3}(25[0-5]|2[0-4]\d|[01]?\d\d?)$|^::([\da-fA-F]{1,4}:){0,4}((25[0-5]|2[0-4]\d|[01]?\d\d?)\.){3}(25[0-5]|2[0-4]\d|[01]?\d\d?)$|^([\da-fA-F]{1,4}:):([\da-fA-F]{1,4}:){0,3}((25[0-5]|2[0-4]\d|[01]?\d\d?)\.){3}(25[0-5]|2[0-4]\d|[01]?\d\d?)$|^([\da-fA-F]{1,4}:){2}:([\da-fA-F]{1,4}:){0,2}((25[0-5]|2[0-4]\d|[01]?\d\d?)\.){3}(25[0-5]|2[0-4]\d|[01]?\d\d?)$|^([\da-fA-F]{1,4}:){3}:([\da-fA-F]{1,4}:){0,1}((25[0-5]|2[0-4]\d|[01]?\d\d?)\.){3}(25[0-5]|2[0-4]\d|[01]?\d\d?)$|^([\da-fA-F]{1,4}:){4}:((25[0-5]|2[0-4]\d|[01]?\d\d?)\.){3}(25[0-5]|2[0-4]\d|[01]?\d\d?)$|^([\da-fA-F]{1,4}:){7}[\da-fA-F]{1,4}$|^:((:[\da-fA-F]{1,4}){1,6}|:)$|^[\da-fA-F]{1,4}:((:[\da-fA-F]{1,4}){1,5}|:)$|^([\da-fA-F]{1,4}:){2}((:[\da-fA-F]{1,4}){1,4}|:)$|^([\da-fA-F]{1,4}:){3}((:[\da-fA-F]{1,4}){1,3}|:)$|^([\da-fA-F]{1,4}:){4}((:[\da-fA-F]{1,4}){1,2}|:)$|^([\da-fA-F]{1,4}:){5}:([\da-fA-F]{1,4})?$|^([\da-fA-F]{1,4}:){6}:$
                              uri:
                                description: URI
                                type: string
                              param:
                                description: 参数列表
                                type: array
                                items:
                                  description: 参数
                                  type: string
                httpflood:
                  description: httpflood
                  type: object
                  required: [ enable,mode,cookie,selfrule ]
                  properties:
                    enable:
                      description: 是否启用
                      type: string
                      enum: [ "on","off" ]
                    mode:
                      description: 工作模式
                      type: string
                      enum: [ prevention,prevention+warning ]
                    cookie:
                      description: cooke挑战开关
                      type: string
                      enum: [ "on","off" ]
                    selfrule:
                      description: 自定义规则开关
                      type: string
                      enum: [ "on","off" ]
                    security:
                      description: 防护策略列表
                      type: array
                      items:
                        description: 防护策略详情
                        type: object
                        required: [ name,monitor,ipRange,maxCc,maxRps ]
                        properties:
                          name:
                            description: 名称
                            type: string
                            pattern: ^[\w-]{1,32}$
                          monitor:
                            description: 控制粒度
                            type: string
                            enum: [ per_ip,per_ip_range ]
                          ipRange:
                            description: IP范围
                            type: object
                            required: [ start,end ]
                            properties:
                              start:
                                description: 开始IP
                                type: string
                                pattern: ^([0-9]|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.([0-9]|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.([0-9]|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.([0-9]|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])$
                              end:
                                description: 结束IP
                                type: string
                                pattern: ^([0-9]|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.([0-9]|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.([0-9]|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.([0-9]|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])$
                          parameters:
                            description: 高级威胁特征
                            type: string
                          maxCc:
                            description: 最大并发连接
                            type: integer
                            minimum: 0
                            maximum: 999999999
                          maxRps:
                            description: 最大HTTP请求速率
                            type: integer
                            minimum: 0
                            maximum: 999999999
                rfc2616Check:
                  description: http协议清洗
                  type: object
                  required: [ enable,checkMode,control ]
                  properties:
                    enable:
                      description: 是否启用HTTP协议清洗
                      type: string
                      enum: [ "on","off" ]
                    attr:
                      description: 合法自定义头列表
                      type: array
                      items:
                        description: 合法自定义头详情
                        type: string
                    checkMode:
                      description: 工作模式
                      type: string
                      enum: [ warning,prevention,prevention+warning ]
                    control:
                      description: 数据检查控制
                      type: string
                      enum: [ req,res,req+res ]
            status:
              description: the status for the WebSecurityProfile resource.
              type: object
              properties:
                state:
                  description: means the resource is valid/invalid in ADC api
                  type: string
                reason:
                  description: the reason for state
                  type: string
                uuid:
                  description: return by ADC api
                  type: string
      served: true
      storage: true
      subresources:
        status: { }
