apiVersion: k8s.tmlake.com/v1
kind: TcpUdpProfile
metadata:
  name: nginxlimit
spec:
  name: nginx_tcpudpprofile_limit
  ipType: "ipv4"
  tcEnable: "off"
  maxbandwidth: 0
  maxConn: 0
  dataPort: 20
  toptEnable: "off"
  toptKind: 28
  ednsEnable: "off"
  tcpRst: 5
  tcpSyn: 120
  tcpEstablished: 900
  tcpFin: 10
  icmp: 5
  udp: 600
  ddos:
    ddosEnable: "on"
    ddosList:
      - name: nginx-ddos
        monitor: entirety
        ipRange:
          start: 192.168.10.1
          end: 192.168.10.1
        maxCc: 1000
        maxCps: 1000
